; This file is automatically generated by the top-level EVEBot.iss

#if ${EVEBotBehaviors.Element[obj_Delegator]}
	#include Behaviors/obj_Delegator.iss
#endif

#if ${EVEBotBehaviors.Element[obj_Ratter]}
	#include Behaviors/obj_Ratter.iss
#endif

